using NUnit.Framework;
using ZMachineLib.Content;
using ZMachineLib.Operations.OP1;

namespace ZMachineLib.Unit.Tests.Operations.OP1
{
    /// <summary>
    /// 1OP:132 4 get_prop_len property-address -> (result)
    /// Get length of property data(in bytes) for the given object's property.
    /// It is illegal to try to find the property length of a property which does
    /// not exist for the given object, and an interpreter should halt with an error
    /// message (if it can efficiently check this condition).
    /// @get_prop_len 0 must return 0. This is required by some Infocom games and files
    /// generated by old versions of Inform.
    /// </summary>
    public class GetPropLenTests : OperationsTestsBase<GetPropLen>
    {
        [SetUp]
        public void SetUp()
        {
            Setup();
        }

        [Test]
        public void Should_return_property_length()
        {
            byte propInfo = 123;
            var expected = ZMachineObject.GetPropertySize(propInfo);
            Mockery
                .SetNextGet(propInfo);

            var args = new OperandBuilder()
                .WithArg(AnyVariable)
                .Build();

            Operation.Execute(args);

            Mockery
                .ResultStored(expected);
        }
    }
}